### PR TITLE
refactor: standard-GEM

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- feat:
  - adhere to [`standard-GEM`](https://github.com/MetabolicAtlas/standard-GEM), by refactoring folder tree and README.md (#232)

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Review by feiranl — APPROVED** [review]
Everything looks good, except there is deletion of one entry of model xml file, if that is ok, then everything is fine.

**Review by mihai-sysbio — APPROVED** [review]
Awesome!

Looking at the `/model/*` files, I see they are named `yeastGEM` instead of the expected `yeast-GEM`. Any thoughts on the `standard-GEM` indication that

> All model files must be named the same as the repository

?

**Comment by edkerk** [comment]
> Awesome!
> 
> Looking at the `/model/*` files, I see they are named `yeastGEM` instead of the expected `yeast-GEM`. Any thoughts on the `standard-GEM` indication that
> 
> > All model files must be named the same as the repository
> 
> ?

I don't see a reason why not to adhere to the `standard-GEM` indication on this, so seems fine to correct this.

**Comment by edkerk** [comment]
> Everything looks good, except there is deletion of one entry of model xml file, if that is ok, then everything is fine.

@feiranl This is an artifact of the empty subSystems. I've now manually removed them (`model=rmfield(model,'subSystems')`) before running `saveYeastModel`. This will be fully fixed when subSystems are added (see #11).

**Comment by mihai-sysbio** [comment]
@edkerk I'm curious, why was 0ef8f3f necessary?

**Comment by edkerk** [comment]
Just for reference, coming back to naming of the model files. In commit 919d396, I also changed the `model.id` field from `yeastGEM` to `yeast-GEM`. However, `-` is not allowed in this ID in SBML, so that it either would end up with an invalid SBML file, or it would end up with a `model.id` that reads `yeast__45__GEM` if replaced with ASCII code as COBRA routinely does. This also raises issues when the model is then loaded with RAVEN or cobrapy instead as these do not automatically modify the IDs to replace ASCII codes. So best to prevent all of this, while `standard-GEM` also does not specify that the model.id should have a certain format, just the model filename. This is now fixed with 0ef8f3f and aab4e8d.

**Review by mihai-sysbio — APPROVED** [review]
Interesting observation with the `-` in SBML. Perhaps it would be nice to add some automated validation of the SBML as a GH Action at some point in the future.

Anyway, everything looks good to me!

**Comment by edkerk** [comment]
@mihai-sysbio Very good point, the SBML documentation is very clear on what is allowed, so it would just involve a few regex-checks.

**Pull request merged**
