### PR TITLE
yeast 8.5.0

### LINKED ISSUE #252: fix: wrong annotation for gene  YGR191W for rxn r_4590
### Description of the issue:

* [YGR191W](https://www.yeastgenome.org/locus/S000003423) is wrongly annotated to reaction `r_4590`. remove this one from the reaction, it can also make sure that the gene [YOL130W](https://www.yeastgenome.org/locus/S000005490) to be essential. 
`r_4592: Mg(2+) transport reaction YGR191W or YOL131W`

* BTW, `YGR191W` is correctly annotated currently to reactions for his transport and Mn(2+) transport.

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---user) for running the model
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

### LINKED ISSUE #254: fix: Wrong annotation for s_1218
S_1218 is currently named "nicotinamide ribose", rather than "nicotinamide riboside", as it should be.

Reference: https://metabolicatlas.org/explore/gem-browser/yeast8/metabolite/s_1218

### LINKED ISSUE #258: doc: rename master and devel branches
### Description of the issue:
- In line with https://github.com/github/renaming, the `master` branch can now be renamed to `main`, which is the new default branch name in GitHub. This will also be applied to [standard-GEM](https://github.com/MetabolicAtlas/standard-GEM/issues/6).
- `standard-GEM` also specifies that the development branch should be named `develop`.

#### Expected feature/value/output:
`main` and `develop` branches

#### Current feature/value/output:
`master` and `devel` branches

#### To do:
- [x] Rename the branches on GitHub. See [instructions](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch).
- [x] Update functions and documentation references to the branch names.
- [x] As [suggested](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes), include instructions on how to update local branch names in the release notes of the next `yeast-GEM` version?

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- Fixes:
  - combine glycolysis + gluconeogenesis as single KEGG pathway (PR #251)
  - rxn: corrects grRule of r_4590 (closes #252)
  - met: corrects name of s_1218 (closes #254)
  - saveYeastModel handles Unicode characters (PR #255)
  - indentation of yeastGEM.yml (contributes to #236)
- Features:
  - memote as GitHub Action for pull requests (PR #162)
  - old subSystems changed to reaction annotation (in `rxnMiriams` or `rxnKEGGpathways`) (PR #253)
- Chore:
  - update dependencies in *requirements.txt (PR #256)
  - minor changes in model file formatting due to updates in COBRA+RAVEN toolboxes (PR #253)
- Refactor:
  - follow `standard-GEM` specifications (PR #257)
  - rename `master` and `devel` branches to `main` and `develop` (closes #258)

**Also rename your local branches to `main` and `develop`:**

```sh
git branch -m master main
git branch -m devel develop
git fetch origin
git branch -u origin/main main
git branch -u origin/develop develop
```

**PR #257 and issue #258 should first be resolved**

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `main` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
It should be possible to just change the target branch in this PR without opening a new one?

**Comment by mihai-sysbio** [comment]
Also, is the intention to resolve #11 as part of this release, or would it be better to postpone it?

**Comment by edkerk** [comment]
I didn't close it manually, but I did just change the name of `devel` to `develop`, in accordance with #258. It might be that GitHub is at the moment still processing the name change, and will reopen it soon again to the newly named branch.

Re #11, this would take longer to resolve, so probably good to postpone to distribute as 2.5.1?

**Comment by mihai-sysbio** [comment]
Oh, interesting side-effect or branch renaming.
Sure, it's okay reserve #11 for a subsequent release.

**Pull request closed without merging**
