### PR TITLE
Volatile Esters & Polyphosphate Reactions

### PR DESCRIPTION
**Pull request by edkerk**
This PR replaces #336, as the previous PR does not allow for additional commits by the maintainers ([reason](https://github.com/orgs/community/discussions/5634)). The text below is copy-pasted from #336, authored by @uliebal.

### Main improvements in this PR:

- Addition of in total 36 reactions: 15 enzymatic reactions, 10 transport and 9 exchange reactions.
- Addition of in total 26 metabolites.
- Addition of in total 1 gene.

 #### Volatile esters
- 8 new distinct ester reactions are introduced, of these 6 had the substrates already in the model and only the ester metabolite was newly added. 
- The esterases have broad substrate flexibility and the existing gene for the esterase was used (YOR126C)
- For two esters, the acid substrate was not available in the model and a new aldehyde dehydrogenase reaction was added to generate the acid.
- The aldehyde dehydrogenase was used from an existing gene (YOR374W or YPL061W) which is supported by literature.
- The ester reactions were added only to the cytoplasm compartment

#### Polyphosphate reactions
- A polyphosphate synthesis reaction was added by which cytoplasmic ATP generates diphosphate in the vacuole.
- The protein Vtc4p is responsible for polyphosphate synthesis, but is part of a heterogeneous protein complex. However, only the direct related gen for Vtc4p, YJL012C, and no complex partners (Vtc1-5) were added to the GPR.
- Transport of polyphosphate between the compartments was added, as supported by literature. The transport mode was copied from the phosphate transport as H+ symport.
- Polyphosphate phosphatase was added for compartments vacuole, mitochondria and nucleus according to literature.
- Inorganic phosphate in the nucleus was added as new metabolite.

#### Developers
- Ulf Liebal: ulf.liebal@rwth-aachen.de
- Lars M. Blank: lars.blank@rwth-aachen.de
- Hendrik Mengers: hendrik.mengersr@rwth-aachen.de

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `develop` as a target branch (top left drop-down menu)
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
I reorganized the curation code and data files (and will write clearer instructions for future curations), correct some identifiers and made some further modifications.

Two open questions:

- [ ] There are 2-methylbutyrate and isobutyrate assigned to the extracellular compartment, but there is no transport reaction across the cytoplasmic membrane, nor an exchange reaction that would allow for its net production. Is this intentional, or should such reactions be added?
- [ ] I now assigned the volatile ester reactions to the subsystem "Other", is there another one from this list that is more suitable?
<details>
  <summary>Click to show list of subsystems</summary>

- Alanine, aspartate and glutamate metabolism
- Alternate carbon metabolism
- Amino sugar and nucleotide sugar metabolism
- Arachidonic acid metabolism
- Arginine and proline metabolism
- Arginine biosynthesis
- Ascorbate and aldarate metabolism
- Ascospore biosynthesis
- Beta-alanine metabolism
- Biosynthesis of unsaturated fatty acids
- Biotin metabolism
- Butanoate metabolism
- C5-branched dibasic acid metabolism
- Carnitine metabolism
- Cellular response to anaerobic conditions
- Citrate cycle (TCA cycle)
- Complex alcohol metabolism
- Cyclic nucleotide metabolism
- Cysteine and methionine metabolism
- DNA repair
- Dipeptidases
- Exchange reaction
- Fatty acid biosynthesis
- Fatty acid degradation
- Fatty acid ester pathway
- Folate biosynthesis
- Fructose and mannose metabolism
- Galactose metabolism
- Glutathione metabolism
- Glycerolipid metabolism
- Glycerophospholipid metabolism
- Glycine, serine and threonine metabolism
- Glycolysis / gluconeogenesis
- Glycosylphosphatidylinositol (gpi)-anchor biosynthesis
- Glyoxylate and dicarboxylate metabolism
- Growth
- Histidine metabolism
- Inositol phosphate metabolism
- Insect hormone biosynthesis
- Lipoic acid metabolism
- Lysine metabolism
- Methylglyoxal metabolism
- N-glycan biosynthesis
- Nicotinate and nicotinamide metabolism
- Nitrogen metabolism
- One carbon pool by folate
- Other
- Oxidative phosphorylation
- Pantothenate and coa biosynthesis
- Pentose and glucuronate interconversions
- Pentose phosphate pathway
- Peptidyl-diphthamide biosynthetic process
- Phenylalanine metabolism
- Phenylalanine, tyrosine and tryptophan biosynthesis
- Phosphatidylinositol signaling system
- Porphyrin and chlorophyll metabolism
- Propanoate metabolism
- Purine metabolism
- Pyrimidine metabolism
- Pyruvate metabolism
- Riboflavin metabolism
- SLIME reaction
- Sphingoglycolipid metabolism
- Sphingolipid metabolism
- Starch and sucrose metabolism
- Steroid biosynthesis
- Sulfur metabolism
- Superoxide metabolism
- Taurine and hypotaurine metabolism
- Terpenoid backbone biosynthesis
- Thiamine metabolism
- Threonylcarbamoyladenosine metabolism
- Transport [c, ce]
- Transport [c, e]
- Transport [c, er]
- Transport [c, erm]
- Transport [c, g]
- Transport [c, gm]
- Transport [c, lp]
- Transport [c, m]
- Transport [c, mm]
- Transport [c, n]
- Transport [c, p]
- Transport [c, v]
- Transport [c, vm]
- Transport [ce, erm]
- Transport [e, ce]
- Transport [er, g]
- Transport [erm, er]
- Transport [erm, gm]
- Transport [erm, lp]
- Transport [erm, mm]
- Transport [erm, n]
- Transport [erm, vm]
- Transport [m, mm]
- Transport [m, v]
- Transport [p, m]
- Transport [vm, ce]
- Transport [vm, gm]
- Transport[c, e]
- Tryptophan metabolism
- Tyrosine metabolism
- Ubiquinone and other terpenoid-quinone biosynthesis
- Valine, leucine and isoleucine metabolism
- Vitamin b6 metabolism
- tRNA metabolism

</details>

**Comment by uliebal** [comment]
thanks a lot for the improvements and adaptations!

* 2-methylbutyrate and isobutyrate need no extracellular association. 
They suffice as cytoplasmic intermediates for the ester synthesis.

* The volatile ester reactions fit better to the subsystem 'Fatty acid 
ester pathway' than 'Other'

**Comment by mihai-sysbio** [comment]
Seeing these new contributions, I'm wondering if yeast-GEM wouldn't also benefit from [allcontributors.org](allcontributors.org/) setup, see https://github.com/SysBioChalmers/Human-GEM#contributors - what do others think?

**Comment by edkerk** [comment]
@mihai-sysbio I'm not sure why the `memote-run` GitHub Action fails, especially as `memote-history` succeeds?

Anyway, I've reviewed the changes in this PR (but cannot post a review on my own PR), while the changes were originally committed as #336. I'll therefore force merge without review.

**Comment by mihai-sysbio** [comment]
@edkerk thanks for pinging about this. It was a good call to proceed without investigating.

The workflow runs a Python line before running Memote, to make the model Bigg compliant. This is achieved with a file `code/io.py` which looks like is missing from this PR but exists in branch `develop`. As a one-time workflow failure this is acceptable (although I don't know how this happened), but there shouldn't be failures like this in the future.

**Pull request merged**
