### PR TITLE
fix-rxn-prop:addNewGPRrelations

### PR DESCRIPTION
**Pull request by feiranl**
### Main improvements in this PR:
* This improvement is based on genome annotation for _Saccharomyces cerevisiae_ S288c from five databases (SGD, Uniprot, KEGG, Biocyc and Reactome). Reactions linked to these new annotated genes were extracted from those databases (Uniprot, KEGG, Biocyc and Reactome) and by searching annotated EC numbers in different databases (Rhea and Brenda).
* Add database new annotation detailed information in ComplementaryData/databases/DBnewGeneAnnotation.tsv.
* Add new GPR relations for existing reactions according to database new annotation.

Addresses issue #60 

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
Structurally it looks fine, but it would good to see a brief description on _how_ these GPRs were decided. Doesn't have to be very detailed, but now this is entirely unclear. Can be mentioned in this PR, or could have been in commit messages, but now it is not mentioned anywhere.

**Comment by BenjaSanchez** [comment]
@edkerk the reasoning behind each change can be found in `DBnewGeneAnnotation.tsv`, which contains all new genes added. For instance, rxn `r_0005` has an additional gene `YMR306W` in the gene rule. If you go to `DBnewGeneAnnotation.tsv` and search for `YMR306W`, you'll find that it catalyzes indeed that reaction according to all databases used. The same can be done for all other changes.

**Comment by edkerk** [comment]
As discussed, please provide a short description of where the information regarding gene annotations is coming from, by editing the original pull request message.

**Comment by hongzhonglu** [comment]
@feiranl  could you check 'YAR073W', which may be pseudogene? We should remove gene like this to make sure the quality.

**Comment by BenjaSanchez** [comment]
@feiranl @hongzhonglu any remaining changes? if none I will merge in the afternoon.

**Comment by hongzhonglu** [comment]
@BenjaSanchez  No changes from my side.

**Comment by feiranl** [comment]
@BenjaSanchez No changes from my side.

**Pull request merged**
