### PR TITLE
Feat/SLIME rxns

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:
This PR addresses #21 with a novel way for constraining lipid metabolism (see [SysBioChalmers/SLIMEr](https://github.com/SysBioChalmers/SLIMEr)):
* SLIME rxns replace old ISA rxns for lumping lipids.
* There are now 3 lipid pseudoreactions: 1 constrains backbones, 1 constrains acyl chains, 1 merges both.
* Biomass composition was rescaled to experimental data from [Lahtvee et al. 2017](https://www.sciencedirect.com/science/article/pii/S2405471217300881). 

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
It's unclear to me how you defined the chemical formulae of the pseudo metabolites. Could you show for instance why `triglyceride` has chemical formula `C3H2`?

**Comment by BenjaSanchez** [comment]
@edkerk sure! Let's take `tryglyceride (16:1-16:1-16:1)`: The molecular formula is `C51H92O6`, and the corresponding SLIME rxn creates a backbone + 3 chains of palmitoleic acid `C16H30O2` (note, not palmitoleate, which has one H less). Then I mass balance those formulas: `C51H92O6 - 3*(C16H30O2) = C3H2`, to display clearly that a SLIME rxn is indeed "splitting" the lipid. You can see the code in [addSLIMErxn.m](https://github.com/SysBioChalmers/SLIMEr/blob/2086c3f541a184c9d6b617c01f66bb246d8d4332/models/addSLIMErxn.m#L120). The alternative would be to include the radicals and make the formula `C3H2R3`, or even `C3H6R3`, which looks nicer based on the known structure for triglycerides but double accounts for 3 H's (already included in the acyl chains). Also those both approaches are "unbalanced" in the amount of radicals... Then again SLIME rxns are already unbalanced due to the stoich coeffs so maybe this is not an issue.

image

I would not try to balance the rxns as the stoichiometries would be long decimals, but any of the 3 aforementioned options would be fine by me, so let me know which one you think makes more sense and I can adapt the pipeline to that.

**Comment by edkerk** [comment]
@BenjaSanchez thanks for the clear justification. I think it's important that combining the formulae of backbone + chain ideally yields the full formula (as you detailed `C51H92O6 - 3*(C16H30O2) = C3H2`). I would suggest two options:

1. Use `C3H2R3`-type formulae for backbones. It's not completely balanced, but the names of the backbones suggest that they represent a _complete_ lipid species, and this could be captured by including R.
2. Specify in the metabolite names of backbones that they only represent... backbones. So keep using the `C3H2`-type formulae for backbones, the split reactions are still fully balanced, and no confusion why these backbones have unconventional formulae

**Comment by feiranl** [comment]
@BenjaSanchez @edkerk  I prefer the second option if standing at the point of testing unbalanced reaction and metabolites.

**Comment by BenjaSanchez** [comment]
@feiranl @edkerk the word `backbone` has been included in all corresponding metabolites in the latest commit. Let me know if there is anything else pending.

**Pull request merged**
