### PR TITLE
chore: update COBRA

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:
Updated COBRA. No content changes in model (`.xml` & `.yml` don't change), only the number of decimals in some stoichiometric coefficients in `.txt`, most likely due to https://github.com/opencobra/cobratoolbox/pull/1294

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by BenjaSanchez** [comment]
@feiranl could you check that no changes are observed in the `.txt` file in MAC if you go through an I/O cycle?

**Comment by feiranl** [comment]
The .txt file has changed, mainly because coefficients are a little bit different. For example, in the reaction r_4048, the coefficient for s_001[ce] has changed from 0.71609 to 0.716087.

r_4048	0.71609 s_0001[ce] + 0.23919 s_0004[ce] + 0.28569 s_0773[c] + 0.68015 s_1107[c] + 0.11505 s_1520[c]  -> s_3718[c] 		  0.00	1000.00	  0.00
r_4048	0.716087 s_0001[ce] + 0.239185 s_0004[ce] + 0.285686 s_0773[c] + 0.680151 s_1107[c] + 0.115049 s_1520[c]  -> s_3718[c] 		  0.00	1000.00	  0.00

**Comment by BenjaSanchez** [comment]
@feiranl are you sure you are doing the analysis in `chore/COBRAupdate`? The coefficient in this branch for that rxn/met is already 0.716087

**Comment by feiranl** [comment]
Everything is fine when I switch to this branch, it is okay to merge.

**Pull request merged**
