### PR TITLE
yeast 8.6.3

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- Feature:
  - New reactions and metabolites related to volatile esters & polyphosphates (PR #337)

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `main` as a target branch (top left drop-down menu)
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
@mihai-sysbio I don't understand why `memote-run` keeps on failing.

**Comment by mihai-sysbio** [comment]
Well, it looks like there could be two issues (at the same time):

A) Something to do with the permissions
```
touch: cannot touch '.env': Permission denied
```

B) Dependencies are not installed (perhaps they have been changed also since the previous release?)
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/code/io.py", line 8, in <module>
    from dotenv import find_dotenv
ModuleNotFoundError: No module named 'dotenv'
```
The workflow is missing this line from the README:
```
pip install -r code/requirements/requirements.txt  # installs all dependencies
```
which is of course faster (the installation takes forever).

**Comment by mihai-sysbio** [comment]
This also begs the question how come the `.github/workflows` are different in `/main` and `/develop`.

**Comment by mihai-sysbio** [comment]
@edkerk please see PR #341 - once that is merged in `develop`, it should allow the failed workflow to re-run successfully

**Comment by edkerk** [comment]
So not to delay further model progress, I'll merge this PR, the failing `memote run` can also be solved in another Issue/PR.

**Comment by mihai-sysbio** [comment]
> Not sure why it's failing, the models is loaded, memote is running. Some tests are failing, but that shouldn't trigger the Action to fail?

An action/workflow fails based on the exist code of the command. I presume the python command exited with an code of non-zero, indicating error, because of:

```
 Storing result in 'result.json.gz'.
Traceback (most recent call last):
  File "/usr/local/bin/memote", line 8, in <module>
    sys.exit(cli())
[...]
  File "/usr/local/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: 'result.json.gz'
```

This means the result gzip doesn't get created, likely because of the same file permission issue like above about the `.env` file.

**Pull request merged**
