### PR TITLE
fix: FA ester additions

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:

Fixing pending issues in #190:

* Removed non-compliant character that created a bug when loading the model into Matlab.
* Simplified metabolite annotation data file to not require compartment info.
* Added chemical formulas, charges, ChEBI ids and KEGG ids to metabolites.
* Added KEGG pathway ids to reactions.
* Corrected met/rxn notes to point to the proper PR #.

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Review by edkerk — CHANGES_REQUESTED** [review]
@wtscott31 
A few reactions are chemically inbalanced. I've fixed a few, but can't resolve `r_4696` and `r_4697`

In the first one, one O is missing on the left side of the equation, while in the second one there should be 2 methanethiol, but then there is still 2 H missing on the right side of the equation.

<details><summary>Code to identify unbalanced reactions</summary>

```matlab
bs  = getElementalBalance(model);
idx = find(bs.balanceStatus==0)
[~, exch] = getExchangeRxns(model);
idx=setdiff(idx,exch,'stable');
out = model.rxns(idx);
for i=1:length(idx)
    dif = bs.leftComp(idx(i),:) - bs.rightComp(idx(i),:);
    mets = find(~dif==0);
    difference = '';
    for j=1:length(mets)
        difference = strcat(difference,bs.elements.abbrevs(mets(j)));
        difference = strcat(difference,num2str(dif(mets(j))));
    end
    out(i,2) = difference;
end
```
</details>

@BenjaSanchez 
EC numbers are not always exactly for the right reaction, `r_4696` uses methanethiol instead of glutathione (EC2.8.1.3](https://enzyme.expasy.org/EC/2.8.1.3). What EC number should be annotated to such a reaction? Or maybe 2.8.3.-? Similar are the aldehyde dehydrogenases.

**Comment by wtscott31** [comment]
> @wtscott31
> A few reactions are chemically inbalanced. I've fixed a few, but can't resolve `r_4696` and `r_4697`
> 
> In the first one, one O is missing on the left side of the equation, while in the second one there should be 2 methanethiol, but then there is still 2 H missing on the right side of the equation.
> 
> @BenjaSanchez
> EC numbers are not always exactly for the right reaction, `r_4696` uses methanethiol instead of glutathione (EC2.8.1.3](https://enzyme.expasy.org/EC/2.8.1.3). What EC number should be annotated to such a reaction? Or maybe 2.8.3.-? Similar are the aldehyde dehydrogenases.

Hi @edkerk yes I see now that 'r_4696' is imbalance. I think your suggestion for that is correct. For ' r_4697' somehow that reaction was incorrectly inputted because it is cited here:https://www.uniprot.org/uniprot/Q08742   as hydrogen cyanide + thiosulfate = 2 H+ + sulfite + thiocyanate. Therefore hydrogen cyanide and thiocyanate have to be included and methanethiol and dimethyl disulfide should be removed.

**Comment by edkerk** [comment]
@wtscott31 
> Hi @edkerk yes I see now that 'r_4696' is imbalance. I think your suggestion for that is correct. For ' r_4697' somehow that reaction was incorrectly inputted because it is cited here:https://www.uniprot.org/uniprot/Q08742 as hydrogen cyanide + thiosulfate = 2 H+ + sulfite + thiocyanate. Therefore hydrogen cyanide and thiocyanate have to be included and methanethiol and dimethyl disulfide should be removed.
How should `r_4696` be fixed? I see only that an O is missing, no idea how to fix this.

**Comment by edkerk** [comment]
@wtscott31 And your proposed scheme for `r_4697`, from Uniprot, is already included in the model as `r_4326`. So `r_4697` can be discarded?

**Comment by wtscott31** [comment]
> @wtscott31 And your proposed scheme for `r_4697`, from Uniprot, is already included in the model as `r_4326`. So `r_4697` can be discarded?

ok yes then it should be deleted. Sorry about that.

**Comment by edkerk** [comment]
> > @wtscott31
> > > Hi @edkerk yes I see now that 'r_4696' is imbalance. I think your suggestion for that is correct. For ' r_4697' somehow that reaction was incorrectly inputted because it is cited here:https://www.uniprot.org/uniprot/Q08742 as hydrogen cyanide + thiosulfate = 2 H+ + sulfite + thiocyanate. Therefore hydrogen cyanide and thiocyanate have to be included and methanethiol and dimethyl disulfide should be removed.
> > 
> > 
> > How should `r_4696` be fixed? I see only that an O is missing, no idea how to fix this.
> 
> I think if we add a hydroxyl reactant it should work, Right? see link:https://yeast.biocyc.org/YEAST/NEW-IMAGE?type=REACTION&object=RXN-12539

To balance that reaction: yes. But `hydroxyl radical` is not produced/consumed by any other reaction, which would then make `r_4696` a dead-end reaction. To me it also seems unlikely that hydroxyl radical is a real substrate here, and in MetaCyc it is rather added to just balance the equation. What evidence is there for this reaction?

**Comment by wtscott31** [comment]
> > > @wtscott31
> > > > Hi @edkerk yes I see now that 'r_4696' is imbalance. I think your suggestion for that is correct. For ' r_4697' somehow that reaction was incorrectly inputted because it is cited here:https://www.uniprot.org/uniprot/Q08742 as hydrogen cyanide + thiosulfate = 2 H+ + sulfite + thiocyanate. Therefore hydrogen cyanide and thiocyanate have to be included and methanethiol and dimethyl disulfide should be removed.
> > > 
> > > 
> > > How should `r_4696` be fixed? I see only that an O is missing, no idea how to fix this.
> > 
> > 
> > I think if we add a hydroxyl reactant it should work, Right? see link:https://yeast.biocyc.org/YEAST/NEW-IMAGE?type=REACTION&object=RXN-12539
> 
> To balance that reaction: yes. But `hydroxyl radical` is not produced/consumed by any other reaction, which would then make `r_4696` a dead-end reaction. To me it also seems unlikely that hydroxyl radical is a real substrate here, and in MetaCyc it is rather added to just balance the equation. What evidence is there for this reaction?

I also see it does not have an EC number as well.

**Comment by wtscott31** [comment]
> > EC numbers are not always exactly for the right reaction, r_4696 uses methanethiol instead of glutathione (EC2.8.1.3). What EC number should be annotated to such a reaction? Or maybe 2.8.3.-? Similar are the aldehyde dehydrogenases.
> 
> @edkerk you meant `r_4697` right? As that reaction was removed, the issue is solved. Regarding aldehyde dehydrogenases, I would say in general that EC numbers should match exactly, and the parent (e.g. `1.1.1.-`) should only be used if we are sure that said generalization can be made. @wtscott31 what was your criteria for assigning those EC numbers?
> 
> > There is not that much literature about the reaction. However, I think this reaction occurs spontaneously during alcoholic fermentation.
> 
> The yeast model should only contain reactions for which there is clear evidence of their existence, otherwise we risk expanding too much based on hypothetical reactions. Therefore, I think this reaction (and any others that PR #190 added that do not have any evidence) should be removed.

Hi @BenjaSanchez, r_4696 are contains no EC number as far as I know so I am fine with it if you want to remove it. I know is occurs spontaneously without an enzyme. r_4697 was/is stoichiometrically imbalanced. Here is the source of that reaction:https://yeast.biocyc.org/YEAST/NEW-IMAGE?type=REACTION&object=RXN-8202. I think the reaction I entered needs an methanethiol as a reactant and a hydrogen ion. However, the EC number is correct I presume. I always check KEGG and BRENDA databases for the EC numbers and other reaction info. Some reactions are general though which required me to check stoichiometry, but the others should be okay.

**Comment by BenjaSanchez** [comment]
> r_4696 are contains no EC number as far as I know so I am fine with it if you want to remove it. I know is occurs spontaneously without an enzyme.

The only way this reaction can stay is if you provide literature that shows that it indeed happens spontaneously.

> I always check KEGG and BRENDA databases for the EC numbers and other reaction info

Here I believe @edkerk was asking about aldehyde dehydrogenases specifically. @edkerk could you be more specific on which aldehyde dehydrogenases seem to have mismatched EC numbers?

**Comment by wtscott31** [comment]
> > r_4696 are contains no EC number as far as I know so I am fine with it if you want to remove it. I know is occurs spontaneously without an enzyme.
> 
> The only way this reaction can stay is if you provide literature that shows that it indeed happens spontaneously.
> 
> > I always check KEGG and BRENDA databases for the EC numbers and other reaction info
> 
> Here I believe @edkerk was asking about aldehyde dehydrogenases specifically. @edkerk could you be more specific on which aldehyde dehydrogenases seem to have mismatched EC numbers?

Ok r_4696 can be removed since we cannot find it in a database for yeast.

**Comment by BenjaSanchez** [comment]
@edkerk both `r_4696` and `r_4697` are now deleted. Let me know if there are any remaining issues here so that we can merge and have a functional model in `devel`.

**Review by edkerk — APPROVED** [review]

**Pull request merged**
