### PR TITLE
fix/interOSissues

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:
Addresses issue #96: regardless if the model is saved with a windows or a MAC machine, the .xml file is now stored with the same scientific format

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by BenjaSanchez** [comment]
@hongzhonglu can you test this in your OS? in this branch, go through a I/O cycle and let me know if any model files are changing

**Comment by hongzhonglu** [comment]
@BenjaSanchez  I will do it today!

**Comment by hongzhonglu** [comment]
Hello, Benjamin,
This is the test result when run the I/O cycle I OS:

[cid:image001.png@01D3F841.5EAC01D0]

[cid:image002.png@01D3F841.5EAC01D0]

Best regards,
Hongzhong

**Comment by BenjaSanchez** [comment]
@hongzhonglu I think images cannot be pasted when you reply via email, as I cannot see the results. Are any of the model files changing?

**Comment by hongzhonglu** [comment]
One place in xml file has been changed.

Best regards,
Hongzhong

**Comment by BenjaSanchez** [comment]
@hongzhonglu could you show me how did it change? did you do it with the latest version of this branch? if you reply in Github you can embed pictures

**Comment by hongzhonglu** [comment]
@BenjaSanchez 
These are changes in the test:
image
image
I  use latest branch of dev, load model and then save the model.

**Comment by BenjaSanchez** [comment]
@hongzhonglu you have to switch to branch `fix/interOSissues` (and pull all recent changes), as the changes are there. `devel` does not have any of the changes in this PR yet.

**Comment by hongzhonglu** [comment]
@BenjaSanchez  You can find the latest test.

**Pull request merged**
