### PR TITLE
ATP synthase mitochondrial complex curation

### PR DESCRIPTION
**Pull request by ae-tafur**
### Main improvements in this PR:

Manually checking the ATP synthase (m) annotation based on portal complex portal (ComplexAc: CPX-3281) and saccharomyces genome database show that the gene rules in r_0226 appears to be incorrect.
 
1. YCL005W-A is a vacuolar atp gene (in 3rd rule). Then, it should no be part of this reaction
2. YJL180C and YLR393W and YNL315C are assembly factors (in 3rd rule). 
3. YDR322C-A is essential for the dimeric and oligomeric state of ATP synthase, and YPR020W is  reversibly phosphorylated on two residues; unphosphorylated form is required for dimerization of the ATP synthase complex, which in turn determines oligomerization of the complex and the shape of inner membrane cristae. Then, both of them should be in at least one rule. Currently, they are separated (YDR322C-A is only in 1st rule and YPR020W 2nd rule, it is the only difference between 1st and 2nd rule).
4. YOL077W-A is associated only with the dimeric form of ATP synthase. Currently, it is only in the 3rd rule. 

So, based on this, I suggest add only two rules:

- Q0080 and Q0085 and Q0130 and YBL099W and YBR039W and YDL004W and YDR298C and YDR377W and YJR121W and YKL016C and YLR295C and YML081C-A and YPL078C and YPL271W and YDR322C-A and YPR020W and YOL077W-A

OR

- Q0080 and Q0085 and Q0130 and YBL099W and YBR039W and YDL004W and YDR298C and YDR377W and YJR121W and YKL016C and YLR295C and YML081C-A and YPL078C and YPL271W and YDR322C-A and YPR020W

However, [Wagner, et al](https://doi.org/10.1091/mbc.e09-12-1023) reports that:  

“Large chain-like assemblies of ATP synthase dimers were observed in the inner mitochondrial membrane (Allen et al., 1989; Buzhynskyy et al., 2007; Strauss et al., 2008). Such dimer ribbons have been proposed to induce membrane bending and eventually lead to the formation of cristae.”

 “Oligomerization of ATP synthase is critical for the morphology of the inner mitochondrial membrane because it supports the generation of tubular cristae membrane domains. Association of individual F(1)F(o)-ATP synthase complexes is mediated by the membrane-embedded F(o)-part”. 

Moreover, deletion of ATP19 (YOL077W-A) had no significant effect on the growth of yeast cells on nonfermentable medium (YPG)

Then, it should be only one gene rule (first one) which combines all the genes in the complex (oligomerization and dimerization)

Q0080 and Q0085 and Q0130 and YBL099W and YBR039W and YDL004W and YDR298C and YDR377W and YJR121W and YKL016C and YLR295C and YML081C-A and YPL078C and YPL271W and YDR322C-A and YPR020W and YOL077W-A

This remove the following genes: 

1.   'YJL180C'
2.  'YLR393W'
3.  'YNL315C’

This also matches [complex portal](https://www.ebi.ac.uk/complexportal/complex/CPX-3281) 

  | atp_complex_curation develop | develop
-- | -- | --
Rxns | 4063 | 4063
Mets | 2744 | 2744
Genes | 1160 | 1163
Accuracy | 0.8816 | 0.8819
TP | 927 | 930
TN | 63 | 63
FP | 96 | 96
FN | 37 | 37

**I hereby confirm that I have:**

- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [ ] Selected `develop` as a target branch (top left drop-down menu)
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by haowang-bioinfo** [comment]
@ae-tafur nice work.

A quick notice, you were saying that `this removes the following genes`, where the `YCL005W-A` was missed.

**Comment by ae-tafur** [comment]
@haowang-bioinfo When I tested in version 8.6.0, it also removes have the gene YCL005W-A, but this gene in the model in the develop branch does not exit. I think it was removed [here]( #7f832029a6cebfdd7ea76369cfb64ade270cdf72)

**Comment by edkerk** [comment]
@ae-tafur, could you please make sure that [this box](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) is ticked? Thanks!

**Comment by ae-tafur** [comment]
> @ae-tafur, could you please make sure that [this box](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) is ticked? Thanks!

It is ticked

**Pull request merged**
