### PR TITLE
Gapfilling

### PR DESCRIPTION
**Pull request by feiranl**
### Main improvements in this PR:
* This PR is to fill the gap for dead end metabolites in the model. Here we only focus on the deadend metabolites that can be fixed by adding a transport reaction.
* `MissingTransDeadEnd.m` is a function that detect this kind of dead end metabolites
* After detect those metabolites, all transport reactions in MetaNet database of this metabolite would be extracted. We choose the most possible reactions to add according to existing transport reactions in the model.
* `addGapfillingRxnToGEM.m` is to update the model with chosen reactions

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
> Here, the gap filling mainly find transport reactions connect the dead metabolites which existed in two different compartments. It will be a little dangerous that if no evidences support the related transport reactions. Can we find the related evidences?

I agree with Hongzhong on this. Taking the list of suggested new transport reactions, can we evaluate what type of transport they are? It seems some of them are probably simple diffusion (cytoplasm <-> nucleus), while others would be facilitated by some protein. Is there evidence for these reactions in yeast or other organisms? There probably is as they are all MetaNetX reactions?

**Comment by feiranl** [comment]
First, we got the list of deadend metabolites due to transport rxns missing. Next step, we go to MetaNetx to search for all transport rxns related to that met, then we find whether our model has the same transport rxn for this met for another compartment or same transport mechanism for similar met to decide which kind of transport rxns that we should add.

Example:
 
`glutathione[er]` is a deadend, according to this rxn: `r_1168 | glutathione transport | glutathione[c] <=> glutathione[v] |   | YDR135C or YLL015W | -1000 | 1000`

we added the simple rxn  for glutathione[er]:`glutathione[c] <=> glutathione[er]`

**Comment by BenjaSanchez** [comment]
@edkerk @hongzhonglu I don't see the problem of adding these rxns as they all have corresponding MetaNetX ids, or perhaps I'm missing something? @feiranl are the predictions when simulating the model before and after these additions changing any fluxes significantly? Could you display those results here somehow?

**Comment by hongzhonglu** [comment]
@BenjaSanchez  I think Feiran has already give the explanation. what I mean is that though the metnetx ids exist, the detailed reaction can be different in the compartment. It is nice to give evidence to show why we can give the related transport reactions.

**Comment by BenjaSanchez** [comment]
@hongzhonglu what is most likely in all these cases is that transport does occur, but there is missing annotation for the specific compartment. So as long as we indicate "unknown transporter" and that the reactions were added due to gap-filling, I think it would be ok. Adding a transport reaction for which there is only evidence in another compartment is common practice in other models such as `human-GEM` I believe, maybe @Hao-Chalmers can confirm this?

**Comment by edkerk** [comment]
@BenjaSanchez. This is what I was missing, either proof or at least clarification why transport reactions were added:

>  So as long as we indicate "unknown transporter" and that the reactions were added due to gap-filling, I think it would be ok.

This is done in 789533dc046435b024c62697912170bfe4a416eb, so it looks good to me!

**Comment by feiranl** [comment]
image
image
This is the result of growth prediction before and after gapfilling. Adding these rxns doesn't change the model prediction.

**Pull request merged**
