### PR TITLE
Feat/memote

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:
The [memote](https://github.com/opencobra/memote) report has been added as a CI tool for assessing changes in the model. For now it looks [messy](http://sysbiochalmers.github.io/yeast-GEM/history_report.html), but most of those problems have to do with the history report generation, so it would not be a problem to merge now. The one thing that worries me is that each `.json` file is ~2 MB, which as we continue development might escalate a bit too fast. @Midnighter @ChristianLieven any ideas on how to reduce the size of those files?

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by BenjaSanchez** [comment]
@Midnighter after switching from JSON to SQLite (as suggested), the size of the report decreased roughly by half (from 2.04 MB down to 1.19 MB); however, the size still increases linearly with the number of commits: a second [test commit](https://github.com/SysBioChalmers/yeast-GEM/pull/162/commits/0c6bc04ad3ebf0fdd68fdafc30203f4c5d5c52d7) increased the size of `results.db` from [1.19 MB](https://github.com/SysBioChalmers/yeast-GEM/blob/55bb91de83b395edb2f7471256988f0ca7b71f69/results.db) to [2.37 MB](https://github.com/SysBioChalmers/yeast-GEM/blob/1af16cb107da42477a2932f1988fd37625af7c1a/results.db). This would still make the size of the repo grow quite fast if we merge to `devel`. Is there any other solution to this? If needed I can open an issue at memote for further discussion.

In the meantime, this PR will remain open until (at least) https://github.com/opencobra/memote/issues/500 is addressed, as it would help out significantly with the amount of reports generated. In turn, https://github.com/opencobra/memote/issues/498 should be addressed before running `memote history` on the whole repo (but that can be done on another branch).

**Comment by BenjaSanchez** [comment]
Update: `results.db` is now tracked with [git lfs](https://git-lfs.github.com/), so it will not affect the size of the repo. Thanks a lot @fburic for giving the idea :) The limitation of this approach is that git lfs now becomes a requirement if `memote run` or `memote report history` need to be run locally, so this has been included as a [requirement](https://github.com/SysBioChalmers/yeast-GEM/commit/5d4ef6a62a8259d246041c679d80618dd0a79f6d) in the readme. With that, this PR can be now merged.

**Comment by mihai-sysbio** [comment]
I see the intention of tracking new results in `results.db` for _all_ branches. I would have imagined that this public history would contain only the releases. Instead, I would have guessed that the comparison of each PR between current branch and target branch would have been done though a diff instead of adding new results to the `results.db`.

Looking at the latest version of the report https://sysbiochalmers.github.io/yeast-GEM/history_report.html :
a) Is the chart really meant to look like that or would it be improved by running a new version of memote?
b) There are a bunch of results which I suspect are not interesting (eg origin/*), should they be removed from results.db?

**Comment by Midnighter** [comment]
The history report definitely has many opportunities for improvement. Problems are:

1. At the moment, local and remote branches are considered. Maybe we should let the branches be configurable so that only few are shown? Maybe we should only show remote branches by default?
2. Too many commits are not useful as the x-axis labelling becomes useless. We could take only the last x (=10) commits for each branch and show those.

Please note that the `result.db` contains reports by commit hash. So even though we show duplicate branches in the figure the results are unique.

**Comment by mihai-sysbio** [comment]
I think I get it now, the history report expects a git repository with a specific structure in order to produce the report by [navigating the history](https://github.com/opencobra/memote/blob/master/src/memote/suite/reporting/history.py#L79). Boy, was I wrong; my intuitive understanding was that one could run the history report which would append the result from the model passed as argument to a collection of previous results. With that setup, one could produce a report of any series of models versions by navigating through a collection of commits.

**Comment by Midnighter** [comment]
> With that setup, one could produce a report of any series of models versions by navigating through a collection of commits.

Actually, you can already (re-)calculate the results for a git commit range `<SHA1>..<SHA1>`. We could let the `memote report history` command also take such a range as an argument and only draw the results for commits in that range.

**Comment by mihai-sysbio** [comment]
I see. What I meant by "a collection of commits" is a series of commit hashes, a bit more granular than a git-based commit range. I'm still having difficulties with running "history_report" in #239 . Is that PR the last step that is needed, or would is the completion of opencobra/memote#498 still required, as initially mentioned above?

**Comment by Midnighter** [comment]
While https://github.com/opencobra/memote/issues/498 would be a big improvement, I don't think it's strictly necessary. Or what do you think?

**Comment by mihai-sysbio** [comment]
@Midnighter, personally I think the more decoupled `memote` is from the structure of a repository, the easier it is to use in different automated setups. So I would go even further than opencobra/memote#498, by allowing the user to decide what the report should include instead of forcefully running the entire history. However, as you say, this is not strictly necessary here.

Since #239 builds on the work here and is ready for merging, I think the current PR can safely be closed.

**Comment by Midnighter** [comment]
> @Midnighter, personally I think the more decoupled `memote` is from the structure of a repository, the easier it is to use in different automated setups. So I would go even further than [opencobra/memote#498](https://github.com/opencobra/memote/issues/498), by allowing the user to decide what the report should include instead of forcefully running the entire history. However, as you say, this is not strictly necessary here.
> 
> Since #239 builds on the work here and is ready for merging, I think the current PR can safely be closed.

Could you open an issue on memote, please, outlining what you would like to be able to specify and how you envision that to work?

**Comment by mihai-sysbio** [comment]
> Could you open an issue on memote, please, outlining what you would like to be able to specify and how you envision that to work?

I tried to give a comprehensive description in opencobra/memote#715.

**Comment by mihai-sysbio** [comment]
From the last Action log I see everything worked up until pushing to `gh-pages`. That branch seems to be protected - how can we make that work with the `memote` reports?

**Comment by edkerk** [comment]
@mihai-sysbio Should the `gh-pages` issue not be resolved before merging? Although I cannot find a solution for it...

**Comment by mihai-sysbio** [comment]
The protected branches are configured in the repository settings, so one thing would be to adjust the settings there and try the action again.

**Comment by edkerk** [comment]
`gh-pages` is no longer a protected branch, and now the all 3 Actions succeed.
The generated [history report](https://sysbiochalmers.github.io/yeast-GEM/history_report.html) is empty (on my computer), but is this a memote issue that should not preclude merging this PR?

**Comment by mihai-sysbio** [comment]
> The generated [history report](https://sysbiochalmers.github.io/yeast-GEM/history_report.html) is empty (on my computer), but is this a memote issue that should not preclude merging this PR?

Inspecting the page shows a bunch of JavaScript errors:
```
ERROR Error: [data] must be specified
ERROR CONTEXT Object { view: {…}, nodeIndex: 4, nodeDef: {…}, elDef: {…}, elView: {…} }
ERROR TypeError: this.chart is undefined
```
As these are beyond our control, I would think it is acceptable to merge the PR. Just to be on the safe side, it might make sense to run the history report locally, to see that the generated report is identical.

**Review by mihai-sysbio — APPROVED** [review]

**Comment by edkerk** [comment]
Locally it produces exactly the same HTML file.

**Pull request merged**
