### PR TITLE
chore: update *requirements.txt

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- chore:
  - update dependencies in `*requirements.txt` (note format change since pip-tools 5.5.0+)

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [x] Selected `devel` as a target branch (top left drop-down menu)
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Review by mihai-sysbio — APPROVED** [review]
Neat!

**Comment by mihai-sysbio** [comment]
It seems a part of the validation fails likely because of `memote` requiring `travis-encrypt` which, in turn, requires `pyyaml` which clashes with `ruamel.yaml` like this https://stackoverflow.com/questions/9286637/pyyaml-error-attribute-error-no-attribute-load .
Should we keep this part of the validation if we know it will continue to fail for some time?

**Comment by edkerk** [comment]
@mihai-sysbio Skipping that step can indeed be sensible, is there a `memote` issue to track whether this is solved?

Meanwhile, would it not work to change line 38 of `.github/workflows/yaml-validation.yml` from:

```python
        pip install -r requirements/ci-requirements.txt
```
to
```python
        pip install cobra
```
?
As `memote` would probably run in another GH, where the `ci-requirements.txt` could still be used? Or if it should work in the same GH, then first check for valid YAML after `pip install cobra`, then run `pip install -r requirements/ci-requirements.txt` for running memote? All as a workaround, until this issue is solved at memote.

**Comment by mihai-sysbio** [comment]
Great idea @edkerk ! I'm not sure why it doesn't work though - from what I can see in the requirements `cobra` is relying on a single yaml library. Furthermore, when trying this locally I get the same error.

**Comment by mihai-sysbio** [comment]
@edkerk it looks like there is no problem with the dependencies after all, just unexpected indentation in the `yml` file. I've manually fixed that for now in bb81286 and the validation passed.

**Comment by edkerk** [comment]
A few tweaks in the `yml`, now directly generated with RAVEN after commit https://github.com/SysBioChalmers/RAVEN/pull/338/commits/99a4536b94b07968a7bbebfb39922c76be7f4e1a

**Comment by mihai-sysbio** [comment]
> A few tweaks in the `yml`, now directly generated with RAVEN after commit [SysBioChalmers/RAVEN@99a4536](https://github.com/SysBioChalmers/RAVEN/commit/99a4536b94b07968a7bbebfb39922c76be7f4e1a)

nice! imho this PR is ready to be merged

**Pull request merged**
