### PR TITLE
Feat:DB new annotation

### PR DESCRIPTION
**Pull request by feiranl**
### Main improvements in this PR:
* This PR is mainly for adding new reactions and metabolites and GPR rules according to database new annotation.
* We chose those new reactions based on new gene annotation. reactions are from different databases, for further information, please check: /ComplementaryData/databases/DBnewGeneAnnotation.tsv
* addDBnewRxns.m is the function that we used to adding new rxns/mets/GPRs, in this function, it would call for quality control for each new reactions. Quality control includes: Mass/charge balance check and energy/redox production check.

**I hereby confirm that I have:**

- [X] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [X] Selected `devel` as a target branch (top left drop-down menu)
- [X] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
@hongzhonglu I suppose manually curated compartment information is more reliable than automated annotation.

You refer to YAL026C's [Cellular Component annotation by High-Throughput to ER on SGD](https://www.yeastgenome.org/locus/S000000024#go) in contrast to its annotation to [Golgi localisation on UniProt](https://www.uniprot.org/uniprot/P39524#subcellular_location)? In that case Golgi is more reliable.

**Comment by hongzhonglu** [comment]
@edkerk  Thanks for your idea! After check, for some cases, it can also be found that the manually curated compartments from the two sources are different. for example, YEL064C. In the Uniprot(https://www.uniprot.org/uniprot/P39981), it is located in 'Vacuole membrane' while in SGD, it is in 'endoplasmic reticulum'. Quite different! When download the whole location from SGD, the location list of YEL064C is 'vacuole;vacuolar membrane;endoplasmic reticulum;' , so maybe we can using the common locations from these two databases as the final evidence for each gene.

**Comment by hongzhonglu** [comment]
This question is also related to https://github.com/SysBioChalmers/yeast-GEM/issues/61 @feiranl

**Comment by BenjaSanchez** [comment]
The changes discussed here were included in a new PR #142. Therefore, this PR will be closed.

**Pull request closed without merging**
