### PR TITLE
add-rxn.prop: Hydrogen Sulfide Addition

### PR DESCRIPTION
**Pull request by wtscott31**
This is an enhancement to the model to properly account for the pathways responsible for the formation of hydrogen sulfide as well as other volatile sulfur compounds during fermentation (see source:https://academic.oup.com/femsyr/article/17/6/fox058/4056150)

### Main improvements in this PR:
*Try to be as clear as possible: Is it fixing/adding something in the model? Is it an additional test/function/dataset? PLEASE DELETE THIS LINE.*

**I hereby confirm that I have:**

- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/yeast-GEM#required-software---contributor) for running the model
- [ ] Selected `develop` as a target branch (top left drop-down menu)
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
Reviewing this PR, I realized that we did not have an intuitive and straightforward way to make such curations. To fix this, not just for here, but also for future usage, I wrote a function `code/curateMetsRxnsGenes()` that can take standardized TSV files as input, and adds the required metabolites, genes and/or reactions, with various warnings and error messages if something is going wrong. See the updated [code/modelCuration/addSULnewRxn.m](https://github.com/SysBioChalmers/yeast-GEM/pull/300/files#diff-6c5cc77126e2912009441440379adda23c896c3cc00e8b7bee89629c6cdf3cb7) to see how this is run, and notice that the TSV files have some minor changes. This `curateMetsRxnsGenes()` will likely be incorporated in RAVEN in the near future, but for now is distributed with yeast-GEM.

Then, down to the actual model changes:
- There were three transport reactions (cytoplasm <=> extracellular) that were called "exchange", this was corrected.
- Three *real* exchange reactions were added, at the moment only allowing excretion.

To do (@wtscott31) :
- [ ] The gene `YOL164W` is [included](https://github.com/SysBioChalmers/yeast-GEM/pull/300/files#diff-b8d4806f0f3e36f033dcfcca8262d8a83c26463f9ed55687f8b818d6b6e2c50d), but should probably also be [assigned](https://github.com/SysBioChalmers/yeast-GEM/pull/300/files#diff-eed9dffcd56f67bf61d505e72e39071bd4add558e7850083d080c9c1e8c78d51) to a particular reaction. If it is not used in any reaction, there is no need to add it to the model.

Note: the model was exported by using the branch from PR #301 and RAVEN from branch PR [#396](https://github.com/SysBioChalmers/RAVEN/pull/396). Due to various generic model changes (identifiers suffices, sorting of entities etc.), it looks there were massive changes in the model files. Commit https://github.com/SysBioChalmers/yeast-GEM/pull/300/commits/031c9ce22e2326dc9de2df917293f91e5f36d533 is the best representative of *real* model changes related to sulfur metabolism.

**Comment by wtscott31** [comment]
Gene YOL164W has been determined to regulate bacterially derived sulfatase,
which is essential for converting sulfate esters to sulfates (see:
https://www.yeastgenome.org/locus/S000005524). However, stoichiometry gets
tricky when dealing with any known sulfate esters. Perhaps, the reactions
are compound reactions with more than one step. Anyway, since this problem
is hard to pin down, we can remove gene YOL164W for now.

**Comment by edkerk** [comment]
Ok, because also in the article that you cite it shows BDS1 as involved in sulfate ester -> sulfate (Fig 1). But are none of the reactions that you propose to add an example of such a reaction?

**Comment by wtscott31** [comment]
The only example metabolite mentioned in the article for that GPR is sodium
dodecyl sulfate, but I cannot find any KEGG or MetaNetX reactions
associated with sodium dodecyl sulfate. This would be helpful to avoid
stoichiometry problems as it is a large molecule.

**Comment by edkerk** [comment]
With commit bbcc58f1c44817a4012e93c1f433c7780bad3524:
- Merged #301, for simpler model I/O.

With commit ef8eaf63595f5bd20206718401a6b2497c57be52:
- Added a few additional metabolite identifiers (MetaNetX, BiGG, BioCyc).
- Curated existing hydrogen sulfide metabolites for consistent identifiers.
- Renamed `2-oxo-3-sulfanylpropanoate` to more recognizable `3-mercaptopyruvate`.

Remaining issues (@wtscott31):
- [ ] The `3-mercaptopyruvate sulfurtransferase` should be corrected. I noticed that `dihydrolipoate disulfide` (DHLA) was annotated with the KEGG ID for [thioredoxin disulfide](https://www.kegg.jp/entry/C00343). Inspecting the cited reference, it seems to refer to [Mikami et al. 2011](http://dx.doi.org/10.1042/BJ20110841), which suggests that both DHLA and thioredoxin are required in mice. Thioredoxin is currently not part of the `3-mercaptopyruvate sulfurtransferase` reaction. Should DHLA (and `dihydrolipoate disulfide`) be replaced with oxidized & reduced thioredoxin?

- [ ] _If_ DHLA should be kept in the reaction above, it does not seems to be recycled: it should also be produced in another reaction, otherwise this pathway is blocked.

- [ ] Related to that, there does not seem to be a purpose for the `dihydrolipoate-diphosphate` reaction: it produces `dihydrolipoyl-AMP` that is not consumed elsewhere. Considering that this is a reaction without gene association, it should be left out.

**Review by edkerk — APPROVED** [review]

**Pull request merged**
